version: '3.7'

services:
  wordpress:
    image: wordpress:apache-xdebug3
    build:
      dockerfile: build/Dockerfile
      context: ./build
    container_name: wordpress
    depends_on:
      - wordpress_db
    ports:
      - "8080:80"
    volumes:
      - ./source:/var/www/html
    #restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress

  wordpress_db:
    image: mysql:5.7
    container_name: wordpress_db
    volumes:
      - db_data:/var/lib/mysql
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - wordpress_db
    #restart: always
    ports:
      - "8888:80"
    environment:
      PMA_HOST: wordpress_db
      MYSQL_ROOT_PASSWORDL: secret
    links:
      - wordpress_db

volumes:
  db_data: {}